# Generated by Django 2.2.2 on 2019-06-15 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteContacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(blank=True, default='Свердловская область', max_length=128, null=True, verbose_name='Область')),
                ('city', models.CharField(blank=True, default='Каменск-Уральский', max_length=128, null=True, verbose_name='Город')),
                ('street', models.CharField(blank=True, default='ул. Заводская, 9/8', max_length=128, null=True, verbose_name='Улица, дом')),
                ('email', models.CharField(blank=True, default='plantalkam@mail.ru', max_length=128, null=True, verbose_name='Email')),
                ('phone1', models.CharField(blank=True, default='+7 (3439) 399-409', max_length=128, null=True, verbose_name='Телефон приёмной')),
                ('phone2', models.CharField(blank=True, default='+7 (3439) 399-409', max_length=128, null=True, verbose_name='Телефон отдела продаж')),
                ('phone3', models.CharField(blank=True, default='+7 (3439) 399-409', max_length=128, null=True, verbose_name='Телефон отдела цветных металлов')),
                ('phone4', models.CharField(blank=True, default='+7 (3439) 399-409', max_length=128, null=True, verbose_name='Телефон бухгалтерии')),
                ('map', models.TextField(blank=True, max_length=500, null=True, verbose_name='Код яндекс карты')),
            ],
            options={
                'verbose_name': 'Контакты',
                'verbose_name_plural': 'Контакты',
            },
        ),
    ]
