# Generated by Django 2.2.2 on 2019-06-15 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tab', models.CharField(max_length=128, verbose_name='Название вкладки')),
                ('title', models.CharField(max_length=128, verbose_name='Заголовок')),
            ],
            options={
                'verbose_name': 'Оборудование',
                'verbose_name_plural': 'Оборудование',
            },
        ),
        migrations.CreateModel(
            name='EquipmentListObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=128, verbose_name='Название оборудования')),
                ('equipment', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='aboutPage.Equipments')),
            ],
            options={
                'verbose_name': 'Название оборудования',
                'verbose_name_plural': 'Названия оборудования',
            },
        ),
        migrations.CreateModel(
            name='EquipmentImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/img/equipments/')),
                ('equipment', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='aboutPage.Equipments')),
            ],
            options={
                'verbose_name': 'Фото оборудования',
                'verbose_name_plural': 'Фото оборудования',
            },
        ),
    ]
