# Generated by Django 2.2.2 on 2019-06-15 12:17

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutPage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipments',
            name='title',
            field=tinymce.models.HTMLField(verbose_name='Заголовок'),
        ),
    ]
