# Generated by Django 2.2.2 on 2019-06-16 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductShopMark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Сплав')),
            ],
            options={
                'verbose_name': 'Марка сплава',
                'verbose_name_plural': 'Марки сплава',
            },
        ),
        migrations.CreateModel(
            name='ProductShopMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Материал')),
            ],
            options={
                'verbose_name': 'Материал',
                'verbose_name_plural': 'Материалы',
            },
        ),
        migrations.CreateModel(
            name='ProductShopType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Вид продукции')),
            ],
            options={
                'verbose_name': 'Вид продукции',
                'verbose_name_plural': 'Виды продукции',
            },
        ),
        migrations.CreateModel(
            name='ProductShop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название')),
                ('thickness', models.CharField(max_length=50, verbose_name='Толщина, мм')),
                ('width', models.CharField(max_length=50, verbose_name='Ширина, мм')),
                ('length', models.CharField(max_length=50, verbose_name='Длина, мм')),
                ('pluck', models.CharField(max_length=50, verbose_name='Плакировка')),
                ('price_per_kilo', models.IntegerField(verbose_name='Цена за кг')),
                ('price_per_unit', models.IntegerField(verbose_name='Цена за штуку')),
                ('is_sale', models.BooleanField(default=False, verbose_name='Товар по распродаже')),
                ('product_mark', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.ProductShopMark', verbose_name='Марка сплава')),
                ('product_material', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.ProductShopMaterial', verbose_name='Материал')),
                ('product_type', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.ProductShopType', verbose_name='Вид продукции')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
    ]
