# Generated by Django 2.2.2 on 2019-06-16 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_productshop_pluck'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productshop',
            name='thickness',
            field=models.FloatField(verbose_name='Толщина, мм'),
        ),
    ]
