# Generated by Django 2.2.2 on 2019-06-15 07:29

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block4Tabs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/img/block4/', verbose_name='Изображение')),
                ('tab_text', models.CharField(max_length=128, verbose_name='Заголовок справа')),
                ('title', models.CharField(max_length=128, verbose_name='Заголовок')),
                ('text', tinymce.models.HTMLField(verbose_name='Текст')),
            ],
        ),
        migrations.CreateModel(
            name='MainPageImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/img/block2/slider/', verbose_name='Изображение')),
            ],
        ),
        migrations.CreateModel(
            name='Sertificates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/img/block5/', verbose_name='Изображение')),
            ],
        ),
    ]
