# Generated by Django 2.2.2 on 2019-06-15 07:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0002_auto_20190615_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sertificates',
            name='date',
            field=models.DateTimeField(default=123456, editable=False),
        ),
    ]
