# Generated by Django 2.2.2 on 2019-12-07 09:43

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Заголовок')),
                ('text', tinymce.models.HTMLField(verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Предложение сотрудничества',
                'verbose_name_plural': 'Предложения сотрудничества',
            },
        ),
    ]
