# Generated by Django 2.2.2 on 2019-06-16 18:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0003_auto_20190616_1335'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=128, verbose_name='Пользователь')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Первый товар положен в корзину')),
                ('apply_date', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Оформление заказа')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Общая стоимость')),
                ('user_name', models.CharField(blank=True, max_length=128, verbose_name='ФИО')),
                ('user_email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('user_phone', models.CharField(blank=True, max_length=128, verbose_name='Номер телефона')),
                ('company_name', models.CharField(blank=True, max_length=128, verbose_name='Название компании')),
                ('user_comment', models.TextField(blank=True, max_length=500, verbose_name='Комментарий')),
                ('delivery_type', models.CharField(blank=True, max_length=128, verbose_name='Тип доставки')),
                ('delivery_date', models.CharField(blank=True, max_length=128, verbose_name='Дата и время доставки')),
                ('delivery_address', models.CharField(blank=True, max_length=128, verbose_name='Адрес доставки')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='ProductInBasket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('units', models.CharField(default='кг', max_length=10)),
                ('price_per_item', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('order', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='basket.Order', verbose_name='Заказ')),
                ('product', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.ProductShop', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Товар в корзине',
                'verbose_name_plural': 'Товары в корзине',
            },
        ),
    ]
