# Generated by Django 2.2.2 on 2019-06-17 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0002_auto_20190617_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery',
            field=models.TextField(blank=True, max_length=256, verbose_name='Доставка'),
        ),
    ]
