# Generated by Django 2.2.2 on 2019-06-15 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Состояние поставки')),
                ('description', models.TextField(max_length=500)),
            ],
            options={
                'verbose_name': 'Состояние поставки',
                'verbose_name_plural': 'Состояния поставки',
            },
        ),
        migrations.CreateModel(
            name='ProductMark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Сплав')),
            ],
            options={
                'verbose_name': 'Марка сплава',
                'verbose_name_plural': 'Марки сплава',
            },
        ),
        migrations.CreateModel(
            name='ProductMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Материал')),
            ],
            options={
                'verbose_name': 'Материал',
                'verbose_name_plural': 'Материалы',
            },
        ),
        migrations.CreateModel(
            name='ProductStandart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Стандарт')),
            ],
            options={
                'verbose_name': 'Стандарт',
                'verbose_name_plural': 'Стандарты',
            },
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Вид продукции')),
            ],
            options={
                'verbose_name': 'Вид продукции',
                'verbose_name_plural': 'Виды продукции',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thickness', models.CharField(max_length=50, verbose_name='Толщина, мм')),
                ('width', models.CharField(max_length=50, verbose_name='Ширина, мм')),
                ('length', models.CharField(max_length=50, verbose_name='Длина, мм')),
                ('pluck', models.CharField(max_length=50, verbose_name='Плакировка')),
                ('product_condition', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.ProductCondition')),
                ('product_mark', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.ProductMark')),
                ('product_material', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.ProductMaterial')),
                ('product_standart', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.ProductStandart')),
                ('product_type', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.ProductType')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
    ]
