# Generated by Django 2.2.2 on 2019-06-16 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_condition',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.ProductCondition', verbose_name='Состояние поставки'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_mark',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.ProductMark', verbose_name='Марка сплава'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_material',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.ProductMaterial', verbose_name='Материал'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_standart',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.ProductStandart', verbose_name='Стандарт'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.ProductType', verbose_name='Вид продукции'),
        ),
    ]
