# Generated by Django 2.2.2 on 2019-06-17 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20190616_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pluck',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Плакировка'),
        ),
    ]
